### ISSUE TITLE
Need to implement the APIs for Entity

### ISSUE THREAD

**Issue by encoreshao** [ekohe/crunchbase4#1]
**Need to implement API lists**

For Entity all endpoint will be GET request - https://app.swaggerhub.com/apis-docs/Crunchbase/crunchbase-enterprise_api/1.0.1#/Entity
 
- [x] organizations
- [x] people
- [x] funding_rounds
- [x] searches
- [x] jobs 
- [x] degrees 
- [x] addresses 
- [x] locations 
- [x] categories 
- [x] category_groups
- [x] ipos 
- [x] funds 
- [x] events 
- [x] event_appearances 
- [x] investments 
- [x] acquisitions 
- [x] press_references 
- [x] ownerships

**Comment by encoreshao** [comment]
> Implemennt a new endpoint investment

**Comment by encoreshao** [comment]
Implemented `fetch(entity_id, card_id)` API, allow user get the entity with card_id data

**Comment by chakming888** [comment]
please note that the latest API version is 1.0.2 - https://app.swaggerhub.com/apis-docs/Crunchbase/crunchbase-enterprise_api/

**Comment by encoreshao** [comment]
- Implemented APIs to get the cards data of Entity
  - fund: (`client.organization(entity_id, 'fund')`)
  - ownership: (`client.organization(entity_id, 'ownership')`)
  - founders: (`client.organization(entity_id, 'founders')`)
  - investors: (`client.organization(entity_id, 'investors')`)
  - jobs: (`client.organization(entity_id, 'jobs')`)
  - headquarters_address: (`client.organization(entity_id, 'headquarters_address')`)

**Comment by encoreshao** [comment]
@chakming888

> please note that the latest API version is 1.0.2 - https://app.swaggerhub.com/apis-docs/Crunchbase/crunchbase-enterprise_api/

Thanks for reminder!  it seems that there is no big change!
