### ISSUE TITLE
Errors are not handled properly

### ISSUE THREAD

**Issue by tobsch** [ekohe/crunchbase4#7]
Sometimes I get the error ```NoMethodError (undefined method `[]' for nil:NilClass)```.

This originates in ```/usr/local/bundle/gems/crunchbase4-0.1.7/lib/crunchbase/utilities/request.rb``` line 49 because it tries to access the wrong properties (message). The real response in this case is ```{"error"=>"failed to parse json entity", "code"=>"CS103"}```

**Comment by encoreshao** [comment]
Thank you @tobsch for reporting!

Could you share your request params and API endpoint with us?

**Comment by tobsch** [comment]
@encoreshao it was a wrongly formatted search / incompatible hash that led to the exception

**Comment by encoreshao** [comment]
@tobsch 

I'm not sure if you still have the problem now.

I have added a new logic for parsing error messages by response type. If needed, use the new version v0.2.0. 

I closed it now, if anything I can do, pls have me know.
